### ISSUE TITLE
Understanding of Basic Configuration and installation of Dot-Deployer

### ISSUE THREAD

**Issue by JazzyM2** [WeConnect/dot-deployer-client#82]
Hello @mikedamm  @gplessis @Tombar ,
I have been trying to work on **dot-deployer** for past 2 weeks, i tried downloading source code, installing dependencies but getting error when running project using **npm** because of no applicationId & installationId. I have read the documentation for developers but no clue how things work.
Can i have more detailed documentation or step by step instructions to get things work. Any help will be very much appreciated.

**Note: I am newbie**

**Comment by gplessis** [comment]
@JazzyM2 Sorry, but Developer Platform does not support dot-deployer.

If you need to deploy your application to Wek8s, you should do it with [WeCTL](https://github.com/WeConnect/wectl). Please reach out to #wectl-support to #tech-service-infra on Slack in you need help.

**Comment by JazzyM2** [comment]
Thanks for letting me know :-)
